### PR TITLE
First setup for dockerization

### PR DESCRIPTION
**Pull request by danielfdsilva**

### CODE REVIEW

**Comment by kamicut** [comment]
@smit1678 this modifies the `worker.js` file to run using a software cron job (`npm cron`), which allows the worker to be dockerized. This breaks backwards compatibility with the `heroku scheduler` deployment mechanism for the worker. Should we remove references to heroku from the docs, or should we aim for compatibility with both docker and heroku deployment?

**Comment by smit1678** [comment]
@kamicut 👍  looks good. Can we fix the build before we merge this though?

**Comment by kamicut** [comment]
@smit1678 fixed!

**Comment by smit1678** [comment]
Ok great @kamicut. Have you tested and run this locally? I just attempted to run this locally and getting: 

```
worker_1  | connection error: { [MongoError: failed to connect to server [localhost:27017] on first connect]
```
```
web_1     | connection error: { [MongoError: failed to connect to server [localhost:27017] on first connect]
```

The web app is running and available at `localhost:4000` but it doesn't seem to be connecting to the database.

**Comment by kamicut** [comment]
@smit1678 strange, it should have started the mongodb container (https://github.com/hotosm/oam-catalog/pull/92/files#diff-4e5e90c6228fd48698d074241c2ba760R3). If you do:

`docker ps -a` does it show that the container quit? If it did, use the mongo container's hash with `docker logs HASH` to see if it threw an error.

**Comment by smit1678** [comment]
All containers start and stay running and they don't quit upon error. Here's the logs for each container: https://gist.github.com/smit1678/56b8865fc70cfeed26ce9767c7b171e1.

**Comment by kamicut** [comment]
@smit1678 very weird, do you have DBNAME maybe in your environment variables? That could potentially be overriding DBURI in the code. Also, what is your docker version? I can try to replicate it, but this branch is working for me locally.

**Comment by smit1678** [comment]
@kamicut Yeah there must be something up with my docker install. I have the latest versions. But I tested this on a digital ocean instance quickly and it does not get the same errors. 👍  to merge.

**Pull request merged**
