### PR TITLE
Add option for multiple uris and associated test

### PR DESCRIPTION
**Pull request by kamicut**
Feature for #61 

cc @scisco @smit1678

### CODE REVIEW

**Comment by mojodna** [comment]
w00t

**Comment by scisco** [comment]
@kamicut :+1:

**Comment by smit1678** [comment]
nice, :+1: Merging.

**Comment by anandthakker** [comment]
Is this going to have an influence on the browser?

**Comment by smit1678** [comment]
@anandthakker i don't think we're pulling the /tms endpoint into the oam-browser quite yet so shouldn't affect quite yet: https://github.com/hotosm/oam-browser/issues/120

**Comment by anandthakker** [comment]
Ah right.  k.

**Pull request merged**
