### PR TITLE
Dynamic tiling-related indexing improvements

### PR DESCRIPTION
**Pull request by mojodna**
These were changes made while (locally) indexing the replacement HOT OIN bucket from a local version of the OIN register.

See also hotosm/oam-uploader-api#52 for more context.

### CODE REVIEW

**Comment by smit1678** [comment]
@mojodna Running these changes locally to test and getting some errors. Since https://github.com/openimagerynetwork/oin-register/pull/16 was already merged, testing this against the live register endpoint.  

```
{ [Error: getaddrinfo ENOTFOUND oin-hotosm.s3.amazonaws.com oin-hotosm.s3.amazonaws.com:80]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'oin-hotosm.s3.amazonaws.com',
  host: 'oin-hotosm.s3.amazonaws.com',
  port: 80 }
/Users/nsmith/github/oam-catalog/controllers/meta.js:141
          if (payload.uuid == null) {
                     ^

TypeError: Cannot read property 'uuid' of undefined
    at Request._callback (/Users/nsmith/github/oam-catalog/controllers/meta.js:141:22)
    at Request.self.callback (/Users/nsmith/github/oam-catalog/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/nsmith/github/oam-catalog/node_modules/request/request.js:1048:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/nsmith/github/oam-catalog/node_modules/request/request.js:969:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickDomainCallback (node.js:396:17)
```

Sticking a `console.log(payload);` just before shows that it's working but at first glance it looks like it's reading both the `IMAGE.json` and `IMAGE_meta.json` files.

**Comment by mojodna** [comment]
Yup, that's why it's checking for the presence of a `uuid` property (effectively filtering out non-`meta` files). Puzzled by the error handling.

**Comment by mojodna** [comment]
Aha, `payload` is null when `request` couldn't parse the response as JSON. In this case, it was running into 2 invalid files: one 0-length, one totally invalid. Addressed in 026028b0556859ffe60c4a17b07d228e8d6cded3

**Comment by smit1678** [comment]
@mojodna 👍  I tested this on new deployment connected to the new register and everything indexed well: https://oam-catalog-dynamic-test.herokuapp.com/meta. Merging.

**Pull request merged**
