### PR TITLE
bump node version, fix #88

### LINKED ISSUE #88: Travis failing, bump node version?
Travis tests fail upon linting errors. Testing this locally quick with a bump up of node from `v0.12` to `v4.5.x` removes these errors. 

@mojodna @danielfdsilva Any issues with bumping it up? Should be aiming for `v6.7`? 

```
/home/travis/build/hotosm/oam-catalog/node_modules/eslint/bin/eslint.js:16
const useStdIn = (process.argv.indexOf("--stdin") > -1),
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

https://travis-ci.org/hotosm/oam-catalog/builds/192644227

### PR DESCRIPTION
**Pull request by smit1678**
Fix #88

### CODE REVIEW

**Comment by danielfdsilva** [comment]
@smit1678 we should add a `.nvmrc` file and the `nvm install` command to the readme

**Comment by smit1678** [comment]
@danielfdsilva 👍  have an example from another repo we can follow?

**Comment by danielfdsilva** [comment]
The uploader for example https://github.com/hotosm/oam-uploader

**Comment by smit1678** [comment]
Going ahead with the merge. `.nvmrc` file seems to have fixed the tests as well.

**Pull request merged**
